<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-E5VLIG60" failures="1" tests="1" name="Default test" time="29.641" errors="0" timestamp="2025-03-13T16:56:56 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="26.983">
    <failure type="java.lang.AssertionError" message="expected [https://petstore.octoperf.com/actions/Account.action] but found [https://petstore.octoperf.com/actions/Catalog.action]">
      <![CDATA[java.lang.AssertionError: expected [https://petstore.octoperf.com/actions/Account.action] but found [https://petstore.octoperf.com/actions/Catalog.action]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.petstore.stepDefinitions.PetLogin.user_login_successfully(PetLogin.java:37)
at âœ½.User login successfully(file:///N:/New%20folder/wipro/Maven/JpetStore_CapstoneProject/src/test/resources/Features/loginPage.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
